### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by ramas-jpg** [ceroy-ak/VSbs#1]
{
  "manifest_version":2,
  "version":"0.5",
  "name":"VSbs e-book Copier",

  "background": {
      "scripts": ["background.js"],
      "persistent": true
    },
    "browser_action":{
      "default_icon": "res/32.png",
      "default_title": "VSbs Print Service",
      "default_popup":"popup.html"
    },
  "icons" :{
      "16" : "res/16.png",
      "32" : "res/32.png",
      "64" : "res/64.png",
      "128" : "res/128.png"
  "permissions": ["declarativeContent", "tabs", "storage", "activeTab", "<all_urls>"]
}
 

![Capturar](https://user-images.githubusercontent.com/17952158/55701086-40ea8580-59a8-11e9-8743-5634089c4011.JPG)

Am I doing something wrong? 

Thank you for developing the tool!!!

**Comment by ceroy-ak** [comment]
Hi
Thanks for bringing this up. Actually the } for the "icons" was missing please check the updated manifest.
